###############################################################################
# Phase control
NXP_RF_CONF_BLK_1={20, 02, 14, 01, A0, 6A, 10, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00}

###############################################################################
# CLIF_SS_TX1_CM_CFG_REG - Mode 2
NXP_RF_CONF_BLK_2={20, 02, 0A, 01, A0, 0D, 06, 60, 95, FF, FF, 0F, 00}

###############################################################################
# CLIF_SS_TX2_CM_CFG_REG - Mode 2
NXP_RF_CONF_BLK_3={20, 02, 0A, 01, A0, 0D, 06, 60, 97, FF, FF, 0F, 00}

###############################################################################
# CLIF_ANACTRL_TX_CONFIG_REG - Mode 2 - To be fixed
NXP_RF_CONF_BLK_4={20, 02, 0A, 01, A0, 0D, 06, 12, 4C, 20, 0A, 00, 00}

###############################################################################
# Disable DLMA
NXP_RF_CONF_BLK_5={20, 02, 0D, 01, A0, AF, 09, 10, 3D, 00, 15, 10, 3D, 00, 15, 00}

NXP_RF_CONF_MAX_NUM=5

###############################################################################
# Core configuration extensions
# It includes
# Wired mode settings A0ED, A0EE
# Tag Detector A040, A041, A043
# Low Power mode A007
# Clock settings A002, A003
# PbF settings A008
# Clock timeout settings A004
# eSE (SVDD) PWR REQ settings A0F2
# Window size A0D8
# DWP Speed   A0D5
# How eSE connected to PN553 A012
# UICC2 bit rate A0D1
# SWP1A interface A0D4
# DWP intf behavior config, SVDD Load activated by default if set to 0x31 A037
# Low power tag detection LPTD for power reduction A068
NXP_CORE_CONF_EXTN={20, 02, 36, 03,
    A0, EC, 01, 01,
    A0, ED, 01, 01,
    A0, 68, 2A, 06, 40, 60, 03, 19, 00, 00, 00, 00, 03, 04, 00, 00, 02, 00, 0F, 00, 02, 00, 0F, A0, 00, A0, 00, 03, FA, 00, 00, 00, 4C, 00, 14, 00, 7D, 00, 05, 7F, 00, 00, 01, 00, 03
}
#       A0, F2, 01, 01,
#       A0, 40, 01, 01,
#       A0, 41, 01, 02,
#       A0, 43, 01, 04,
#       A0, 02, 01, 01,
#       A0, 03, 01, 11,
#       A0, 07, 01, 03,
#       A0, 08, 01, 01
#       }

###############################################################################
# Core configuration settings
NXP_CORE_CONF={ 20, 02, 37, 11,
        28, 01, 00,
        21, 01, 00,
        30, 01, 08,
        31, 01, 03,
        32, 01, 60,
        38, 01, 01,
        33, 04, 01, 02, 03, 04,
        54, 01, 06,
        50, 01, 02,
        5B, 01, 00,
        3E, 01, 00,
        80, 01, 01,
        81, 01, 01,
        82, 01, 0E,
        18, 01, 01,
        68, 01, 01,
        85, 01, 01
        }
